Repository PandasWhoCode/gh-audit-setup, pull requests merged in 2025-04, with the labels that each got.

#14 chore: Update audit_template.md
  audit_template.md
Labels: documentation

#17 chore: Update repo files
  .github/SECURITY.md
  .github/workflows/validate-conventional-commits.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, chore

#18 chore: Update audit_template.md
  audit_template.md
Labels: documentation, chore

#20 chore: update the audit template
  audit_template.md
Labels: documentation, enhancement, chore

#21 chore: fix broken workflow file
  .github/workflows/setup_audit.yaml
  run_audit_prep.sh
Labels: bug, chore

#22 chore: Fix broken workflow more
  .github/workflows/setup_audit.yaml
Labels: chore

#23 chore: go back to better GH auth
  .github/workflows/setup_audit.yaml
Labels: chore

#25 chore: Remove workflow as it is dissatisfactory and we should just run the script from CLI
  .github/workflows/setup_audit.yaml
Labels: chore

#26 chore: Update setup-ci-audit.py and run_audit_prep.sh
  run_audit_prep.sh
  setup-ci-audit.py
Labels: chore
